### ISSUE TITLE
[Idea] Add thumbnail of watching anime (like Spotify)

### ISSUE THREAD

**Issue by badgooooor** [PlayingSpree/AnimeDiscordRichPresence#1]

**Comment by PlayingSpree** [comment]
No can do. Too lazy...

For real tho. Discord cap thumbnail image at 150 and I have to manually upload each one so it kidda impossible. 
![image](https://user-images.githubusercontent.com/15007868/92328147-e8318780-f088-11ea-88a8-680f0aafd47b.png)
