### ISSUE TITLE
How to start "MatchAnimeNameStartText" from the beginning of the string ?

### ISSUE THREAD

**Issue by Lastigros** [PlayingSpree/AnimeDiscordRichPresence#6]
I have an issue where anime websites names begin with the anime name itself and i don't know an ounce of JS --'
I thought of str.substr(0) but it just wouldn't work and i don't know why ;(
Please help me ^^

**Comment by PlayingSpree** [comment]
It's not JS but JSON so str.substr(0) or any code will not work. And to answer your question, just leave MatchAnimeNameStartText blank.
PS. I will rework the program to use full GUI soon anyways.
